Support Azure Migrate Assessment Project (s)
inspec/inspec-azure pull request #426
Opened 2021-08-05 17:03 UTC by sathish-progress

### Description
Support Azure Migrate Assessment Project (s)

### Issues Resolved

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-08-09 06:10 UTC, sa-progress requested changes

2021-08-09 06:10 UTC, sa-progress commented on docs/resources/azure_migrate_assessment_projects.md
> +| lastAssessmentTimestamps       | Storage Redundancy types offered by Azure.                             | `lastAssessmentTimestamp` |
Seems Description is wrong.Please check.

2021-08-24 10:34 UTC, sa-progress approved these changes

2021-09-09 20:12 UTC, IanMadd reviewed
Feedback for @dkumaras

2021-09-09 20:12 UTC, IanMadd commented on docs/resources/azure_migrate_assessment_project.md
> +Also, refer to [Azure documentation](https://docs.microsoft.com/en-us/rest/api/migrate/assessment/projects/get) for other properties available. Any attribute in the response may be accessed with the
```suggestion
Refer to the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/migrate/assessment/projects/get) for other properties available. Access any attribute in the response by separating the key names with a period (`.`).
```

2021-09-09 20:12 UTC, IanMadd commented on docs/resources/azure_migrate_assessment_project.md
> +### Test that the Migrate Assessment Project has a minimum scalingFactor
```suggestion
### Test that the Migrate assessment project has a minimum scaling factor
```

2021-09-15 17:35 UTC, IanMadd approved these changes

2021-09-16 02:48 UTC, sathish-progress commented
@dkumaras , Could you please amend your signature to your commits that is causing the DCO to fail ?

2021-09-16 08:51 UTC, merged