Support azure service bus topics
inspec/inspec-azure pull request #565
Opened 2021-11-23 05:53 UTC by sathish-progress

### Description
Support azure service bus topic(s)

### Issues Resolved
#560 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-02-28 04:16 UTC, soumyo13 commented on README.md
> +- [azure_service_bus_namespaces](docs/resources/azure_service_bus_namespaces.md)
These are not required. these are already there in the https://github.com/inspec/inspec-azure/pull/562/files PR.

2022-02-28 04:17 UTC, soumyo13 commented
Please remove the changes of the azure_service_bus_namespace resource. This is a separate resource.

2022-02-28 04:19 UTC, soumyo13 requested changes

2022-02-28 04:19 UTC, soumyo13 commented on docs/resources/azure_service_bus_topics.md
> +`name`, `namespace_name` and `resource_group` is a required parameter.
```suggestion
`name`, `namespace_name`, and `resource_group` are the required parameters.
```

2022-03-02 11:50 UTC, soumyo13 approved these changes

2022-03-11 16:37 UTC, IanMadd approved these changes

2022-03-11 16:39 UTC, IanMadd commented
I deleted the azure_service_bus_namespace.md and azure_service_bus_namespaces.md files. Let me know if this is wrong and I can add them back.

2022-03-12 06:27 UTC, merged