Support service bus regions
inspec/inspec-azure pull request #566
Opened 2021-11-25 02:59 UTC by sathish-progress

### Description

Support Service Bus Region(s)

### Issues Resolved
#557 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-01-07 08:39 UTC, sa-progress approved these changes

2022-02-28 04:21 UTC, soumyo13 commented
Please remove the files of the azure_service_bus_namespace resource. It is a separate resource.

2022-02-28 04:22 UTC, soumyo13 requested changes
Please remove the files of the azure_service_bus_namespace resource. It is a separate resource.

2022-03-02 11:51 UTC, soumyo13 approved these changes

2022-03-02 11:52 UTC, soumyo13 approved these changes

2022-03-11 17:26 UTC, IanMadd commented
I deleted azure_service_bus_namespace.md and azure_service_bus_namespaces.md. Let me know if this is wrong and I can undo it.

2022-03-11 17:26 UTC, IanMadd approved these changes

2022-03-12 07:44 UTC, merged