Support service bus subscriptions
inspec/inspec-azure pull request #568
Opened 2021-11-26 14:51 UTC by sathish-progress

### Description
Support Service Bus Subscription(s)

### Issues Resolved
#559 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-01-07 08:40 UTC, sa-progress approved these changes

2022-02-28 04:39 UTC, soumyo13 requested changes
Please remove the "azure_service_bus_namespace", azure_service_bus_regions, azure_service_bus_subscription_rule resource related files from this PR. These all are seperate resource.

2022-03-02 11:54 UTC, soumyo13 approved these changes

2022-03-11 17:49 UTC, IanMadd approved these changes

2022-03-12 07:09 UTC, merged