Support azure service fabric mesh apps
inspec/inspec-azure pull request #578
Opened 2021-12-14 04:22 UTC by sathish-progress

### Description
Support azure service fabric mesh app(s)

### Issues Resolved
#570 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-02-28 04:42 UTC, soumyo13 approved these changes
LGTM

2022-02-28 04:46 UTC, soumyo13 requested changes
Terraform files are missing.

2022-03-02 11:55 UTC, soumyo13 approved these changes

2022-03-02 11:55 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_application.rb
> +control 'test the properties of an Azure Service Fabric Mesh Application' do
```suggestion
skip_control 'test the properties of an Azure Service Fabric Mesh Application' do
```

2022-03-02 11:55 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_applications.rb
> +control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```

2022-03-11 18:26 UTC, IanMadd approved these changes

2022-03-12 10:40 UTC, merged