Support azure service fabric mesh service replicas
inspec/inspec-azure pull request #580
Opened 2021-12-14 05:48 UTC by sathish-progress

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec](https://github.com/inspec/inspec-azure/CONTRIBUTING.MD) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-02-28 04:45 UTC, soumyo13 reviewed
Terraform Files are missing.

2022-02-28 04:47 UTC, soumyo13 requested changes
Terraform files are missing.

2022-03-02 11:58 UTC, soumyo13 approved these changes

2022-03-02 11:59 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_replica.rb
> +control 'test the properties of all Azure Service Fabric Mesh Service Replica' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Service Replica' do
```

2022-03-02 11:59 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_replicas.rb
> +control 'test the properties of all Azure Service Fabric Mesh Service Replicas' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Service Replicas' do
```

2022-03-11 19:13 UTC, IanMadd approved these changes

2022-03-12 11:15 UTC, merged