Support azure service fabric mesh volumes
inspec/inspec-azure pull request #581
Opened 2021-12-14 06:31 UTC by sathish-progress

### Description

Support azure service fabric mesh volume(s)

### Issues Resolved
#574 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-02-28 04:47 UTC, soumyo13 requested changes
Terraform files are missing.

2022-03-02 11:58 UTC, soumyo13 approved these changes

2022-03-02 12:00 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volume.rb
> +control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```

2022-03-02 12:00 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volumes.rb
> +control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```

2022-03-02 12:01 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volume.rb
> +skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'Test the properties of the Azure Service Fabric Mesh Application' do
```

2022-03-02 12:02 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volume.rb
> +skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Volumes' do
```

2022-03-02 12:02 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volume.rb
> +skip_control 'Test the properties of the Azure Service Fabric Mesh Application' do
```suggestion
skip_control 'Test the properties of the Azure Service Fabric Mesh Volume' do
```

2022-03-02 12:03 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_volumes.rb
> +skip_control 'test the properties of all Azure Service Fabric Mesh Applications' do
```suggestion
skip_control 'test the properties of all Azure Service Fabric Mesh Volumes' do
```

2022-03-11 19:21 UTC, IanMadd approved these changes

2022-03-12 10:59 UTC, merged