Support azure service fabric mesh nws
inspec/inspec-azure pull request #582
Opened 2021-12-14 07:15 UTC by sathish-progress

### Description

Support Azure Service Fabric Mesh Network(s)

### Issues Resolved
#573 

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-01-07 08:48 UTC, sa-progress approved these changes

2022-02-28 04:45 UTC, soumyo13 requested changes
Terraform Files are missing.

2022-03-02 12:04 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_network.rb
> +control 'test the properties of all Azure Service Fabric Mesh Networks' do
```suggestion
skip_control 'Test the properties of all Azure Service Fabric Mesh Networks' do
```

2022-03-02 12:04 UTC, soumyo13 commented on test/integration/verify/controls/azure_service_fabric_mesh_networks.rb
> +control 'test the properties of all Azure Service Fabric Mesh Networks' do
```suggestion
skip_control 'Testthe properties of all Azure Service Fabric Mesh Networks' do
```

2022-03-02 12:05 UTC, soumyo13 approved these changes

2022-03-11 19:26 UTC, IanMadd approved these changes

2022-03-12 11:45 UTC, merged